import { Injectable } from '@angular/core';
import * as moment from 'moment-timezone';

export interface Timezone {
  iso: string;
  zones: string[];
}

export interface Zone {
  name: string;
  zone: string;
}

export interface SimpleZone extends Zone {
  utcOffset: number;
  utcOffsetString: string;
}

@Injectable()
export class TimezonePickerService {
  /**
   * Convert country ISO code to country name (in english)
   */
  public iso2country(iso: string): string {
    if (countryList[iso] !== undefined && countryList[iso] !== null) {
      return countryList[iso];
    } else {
      return iso;
    }
  }

  /**
   * Gets the list of ISO-codes for all countries
   */
  public getCountries(): string[] {
    const res: string[] = [];
    for (const prop of Object.keys(countryList)) {
      res.push(prop);
    }
    return res;
  }

  /**
   * Get the timezones for each country
   */
  public getZones(): Timezone[] {
    const res: Timezone[] = [];
    for (const prop of Object.keys(zones)) {
      res.push({
        iso: prop,
        zones: zones[prop]
      });
    }

    // Sort by country name
    res.sort((a, b) => {
      const aText = this.iso2country(a.iso).toUpperCase();
      const bText = this.iso2country(b.iso).toUpperCase();
      return aText < bText ? -1 : aText > bText ? 1 : 0;
    });

    return res;
  }

  public getSimpleZones(): Zone[] {
    return simpleZones;
  }

  public simpleZoneToName(zone: string) {
    const res = simpleZones.find(
      x => x.zone.toLowerCase() === zone.toLowerCase()
    );
    if (res) {
      return res.name;
    } else {
      return zone;
    }
  }

  public guessSimpleZone(zone: string = null) {
    let input: string = moment.tz.guess().toString();
    if (zone !== null) {
      input = zone;
    }
    const res = simpleZones.find(
      x => x.zone.toLowerCase() === input.toLowerCase()
    );
    if (res) {
      return res.zone;
    } else {
      const offset: number = moment.tz(input).utcOffset();
      let bestMatch: { diff: number; zone: string };
      simpleZones.forEach(z => {
        const zOffset: number = moment.tz(z.zone).utcOffset();
        const offsetDiff = offset - zOffset;
        if (!bestMatch) {
          bestMatch = { diff: offsetDiff, zone: z.zone };
        } else if (bestMatch.diff > Math.abs(offsetDiff)) {
          bestMatch = { diff: offsetDiff, zone: z.zone };
        }
      });
      return bestMatch.zone;
    }
  }

  public offsetOfTimezone(zone: string, useUTC = false): string {
    let offset: number = moment.tz(zone).utcOffset();
    const neg = offset < 0;
    if (neg) {
      offset = -1 * offset;
    }
    const hours = Math.floor(offset / 60);
    const minutes = (offset / 60 - hours) * 60;
    return `(${useUTC ? 'GMT' : 'UTC'}${neg ? '-' : '+'}${this.rjust(
      hours.toString(),
      2
    )}:${this.rjust(minutes.toString(), 2)})`;
  }

  private rjust(string: string, width: number, padding = '0'): string {
    padding = padding || ' ';
    padding = padding.substr(0, 1);
    if (string.length < width) {
      return padding.repeat(width - string.length) + string;
    } else {
      return string;
    }
  }
}

const zones = {
  AD: ['Europe/Andorra'],
  AE: ['Asia/Dubai'],
  AF: ['Asia/Kabul'],
  AG: ['America/Antigua'],
  AI: ['America/Anguilla'],
  AL: ['Europe/Tirane'],
  AM: ['Asia/Yerevan'],
  AO: ['Africa/Luanda'],
  AQ: [
    'Antarctica/McMurdo',
    'Antarctica/Rothera',
    'Antarctica/Palmer',
    'Antarctica/Mawson',
    'Antarctica/Davis',
    'Antarctica/Casey',
    'Antarctica/Vostok',
    'Antarctica/DumontDUrville',
    'Antarctica/Syowa',
    'Antarctica/Troll'
  ],
  AR: [
    'America/Argentina/Buenos_Aires',
    'America/Argentina/Cordoba',
    'America/Argentina/Salta',
    'America/Argentina/Jujuy',
    'America/Argentina/Tucuman',
    'America/Argentina/Catamarca',
    'America/Argentina/La_Rioja',
    'America/Argentina/San_Juan',
    'America/Argentina/Mendoza',
    'America/Argentina/San_Luis',
    'America/Argentina/Rio_Gallegos',
    'America/Argentina/Ushuaia'
  ],
  AS: ['Pacific/Pago_Pago', 'Pacific/Samoa'],
  AT: ['Europe/Vienna'],
  AU: [
    'Australia/Lord_Howe',
    'Antarctica/Macquarie',
    'Australia/Hobart',
    'Australia/Currie',
    'Australia/Melbourne',
    'Australia/Sydney',
    'Australia/Broken_Hill',
    'Australia/Brisbane',
    'Australia/Lindeman',
    'Australia/Adelaide',
    'Australia/Darwin',
    'Australia/Perth',
    'Australia/Eucla',
    'Australia/Canberra',
    'Australia/Queensland',
    'Australia/Tasmania',
    'Australia/Victoria'
  ],
  AW: ['America/Aruba'],
  AX: ['Europe/Mariehamn'],
  AZ: ['Asia/Baku'],
  BA: ['Europe/Sarajevo'],
  BB: ['America/Barbados'],
  BD: ['Asia/Dhaka'],
  BE: ['Europe/Brussels'],
  BF: ['Africa/Ouagadougou'],
  BG: ['Europe/Sofia'],
  BH: ['Asia/Bahrain'],
  BI: ['Africa/Bujumbura'],
  BJ: ['Africa/Porto-Novo'],
  BL: ['America/St_Barthelemy'],
  BM: ['Atlantic/Bermuda'],
  BN: ['Asia/Brunei'],
  BO: ['America/La_Paz'],
  // BQ: ['America/Kralendijk'], // Special municipality of the Netherlands
  BR: [
    'America/Noronha',
    'America/Belem',
    'America/Fortaleza',
    'America/Recife',
    'America/Araguaina',
    'America/Maceio',
    'America/Bahia',
    'America/Sao_Paulo',
    'America/Campo_Grande',
    'America/Cuiaba',
    'America/Santarem',
    'America/Porto_Velho',
    'America/Boa_Vista',
    'America/Manaus',
    'America/Eirunepe',
    'America/Rio_Branco'
  ],
  BS: ['America/Nassau'],
  BT: ['Asia/Thimphu'],
  BW: ['Africa/Gaborone'],
  BY: ['Europe/Minsk'],
  BZ: ['America/Belize'],
  CA: [
    'America/St_Johns',
    'America/Halifax',
    'America/Glace_Bay',
    'America/Moncton',
    'America/Goose_Bay',
    'America/Blanc-Sablon',
    'America/Toronto',
    'America/Nipigon',
    'America/Thunder_Bay',
    'America/Iqaluit',
    'America/Pangnirtung',
    'America/Resolute',
    'America/Atikokan',
    'America/Rankin_Inlet',
    'America/Winnipeg',
    'America/Rainy_River',
    'America/Regina',
    'America/Swift_Current',
    'America/Edmonton',
    'America/Cambridge_Bay',
    'America/Yellowknife',
    'America/Inuvik',
    'America/Creston',
    'America/Dawson_Creek',
    'America/Vancouver',
    'America/Whitehorse',
    'America/Dawson',
    'America/Montreal',
    'Canada/Atlantic',
    'Canada/Central',
    'Canada/Eastern',
    'Canada/Mountain',
    'Canada/Newfoundland',
    'Canada/Pacific',
    'Canada/Saskatchewan',
    'Canada/Yukon'
  ],
  CC: ['Indian/Cocos'],
  CD: ['Africa/Kinshasa', 'Africa/Lubumbashi'],
  CF: ['Africa/Bangui'],
  CG: ['Africa/Brazzaville'],
  CH: ['Europe/Zurich'],
  CI: ['Africa/Abidjan'],
  CK: ['Pacific/Rarotonga'],
  CL: [
    'America/Santiago',
    'Pacific/Easter',
    'Chile/Continental',
    'Chile/EasterIsland'
  ],
  CM: ['Africa/Douala'],
  CN: [
    'Asia/Shanghai',
    'Asia/Harbin',
    'Asia/Chongqing',
    'Asia/Urumqi',
    'Asia/Kashgar'
  ],
  CO: ['America/Bogota'],
  CR: ['America/Costa_Rica'],
  CU: ['America/Havana'],
  CV: ['Atlantic/Cape_Verde'],
  CW: ['America/Curacao'],
  CX: ['Indian/Christmas'],
  CY: ['Asia/Nicosia'],
  CZ: ['Europe/Prague'],
  DE: ['Europe/Berlin'],
  DJ: ['Africa/Djibouti'],
  DK: ['Europe/Copenhagen'],
  DM: ['America/Dominica'],
  DO: ['America/Santo_Domingo'],
  DZ: ['Africa/Algiers'],
  EC: ['America/Guayaquil', 'Pacific/Galapagos'],
  EE: ['Europe/Tallinn'],
  EG: ['Egypt'],
  EH: ['Africa/El_Aaiun'],
  ER: ['Africa/Asmara'],
  ES: ['Europe/Madrid', 'Africa/Ceuta', 'Atlantic/Canary'],
  ET: ['Africa/Addis_Ababa'],
  FI: ['Europe/Helsinki'],
  FJ: ['Pacific/Fiji'],
  FK: ['Atlantic/Stanley'],
  FM: ['Pacific/Chuuk', 'Pacific/Pohnpei', 'Pacific/Kosrae'],
  FO: ['Atlantic/Faroe'],
  FR: ['Europe/Paris'],
  GA: ['Africa/Libreville'],
  GB: ['Europe/London'],
  GD: ['America/Grenada'],
  GE: ['Asia/Tbilisi'],
  GF: ['America/Cayenne'],
  GG: ['Europe/Guernsey'],
  GH: ['Africa/Accra'],
  GI: ['Europe/Gibraltar'],
  GL: [
    'America/Godthab',
    'America/Danmarkshavn',
    'America/Scoresbysund',
    'America/Thule'
  ],
  GM: ['Africa/Banjul'],
  GN: ['Africa/Conakry'],
  GP: ['America/Guadeloupe'],
  GQ: ['Africa/Malabo'],
  GR: ['Europe/Athens'],
  GS: ['Atlantic/South_Georgia'],
  GT: ['America/Guatemala'],
  GU: ['Pacific/Guam'],
  GW: ['Africa/Bissau'],
  GY: ['America/Guyana'],
  HK: ['Asia/Hong_Kong'],
  HN: ['America/Tegucigalpa'],
  HR: ['Europe/Zagreb'],
  HT: ['America/Port-au-Prince'],
  HU: ['Europe/Budapest'],
  ID: ['Asia/Jakarta', 'Asia/Pontianak', 'Asia/Makassar', 'Asia/Jayapura'],
  IE: ['Europe/Dublin'],
  IL: ['Asia/Jerusalem'],
  IM: ['Europe/Isle_of_Man'],
  IN: ['Asia/Kolkata'],
  IO: ['Indian/Chagos'],
  IQ: ['Asia/Baghdad'],
  IR: ['Asia/Tehran'],
  IS: ['Atlantic/Reykjavik'],
  IT: ['Europe/Rome'],
  JE: ['Europe/Jersey'],
  JM: ['America/Jamaica'],
  JO: ['Asia/Amman'],
  JP: ['Asia/Tokyo'],
  KE: ['Africa/Nairobi'],
  KG: ['Asia/Bishkek'],
  KH: ['Asia/Phnom_Penh'],
  KI: ['Pacific/Tarawa', 'Pacific/Enderbury', 'Pacific/Kiritimati'],
  KM: ['Indian/Comoro'],
  KN: ['America/St_Kitts'],
  KP: ['Asia/Pyongyang'],
  KR: ['Asia/Seoul'],
  KW: ['Asia/Kuwait'],
  KY: ['America/Cayman'],
  KZ: [
    'Asia/Almaty',
    'Asia/Qyzylorda',
    'Asia/Aqtobe',
    'Asia/Aqtau',
    'Asia/Oral'
  ],
  LA: ['Asia/Vientiane'],
  LB: ['Asia/Beirut'],
  LC: ['America/St_Lucia'],
  LI: ['Europe/Vaduz'],
  LK: ['Asia/Colombo'],
  LR: ['Africa/Monrovia'],
  LS: ['Africa/Maseru'],
  LT: ['Europe/Vilnius'],
  LU: ['Europe/Luxembourg'],
  LV: ['Europe/Riga'],
  LY: ['Africa/Tripoli'],
  MA: ['Africa/Casablanca'],
  MC: ['Europe/Monaco'],
  MD: ['Europe/Chisinau'],
  ME: ['Europe/Podgorica'],
  MF: ['America/Marigot'],
  MG: ['Indian/Antananarivo'],
  MH: ['Pacific/Majuro', 'Pacific/Kwajalein'],
  MK: ['Europe/Skopje'],
  ML: ['Africa/Bamako'],
  MM: ['Asia/Rangoon'],
  MN: ['Asia/Ulaanbaatar', 'Asia/Hovd', 'Asia/Choibalsan'],
  MO: ['Asia/Macau'],
  MP: ['Pacific/Saipan'],
  MQ: ['America/Martinique'],
  MR: ['Africa/Nouakchott'],
  MS: ['America/Montserrat'],
  MT: ['Europe/Malta'],
  MU: ['Indian/Mauritius'],
  MV: ['Indian/Maldives'],
  MW: ['Africa/Blantyre'],
  MX: [
    'America/Mexico_City',
    'America/Cancun',
    'America/Merida',
    'America/Monterrey',
    'America/Matamoros',
    'America/Mazatlan',
    'America/Chihuahua',
    'America/Ojinaga',
    'America/Hermosillo',
    'America/Tijuana',
    'America/Santa_Isabel',
    'America/Bahia_Banderas'
  ],
  MY: ['Asia/Kuala_Lumpur', 'Asia/Kuching'],
  MZ: ['Africa/Maputo'],
  NA: ['Africa/Windhoek'],
  NC: ['Pacific/Noumea'],
  NE: ['Africa/Niamey'],
  NF: ['Pacific/Norfolk'],
  NG: ['Africa/Lagos'],
  NI: ['America/Managua'],
  NL: ['Europe/Amsterdam'],
  NO: ['Europe/Oslo'],
  NP: ['Asia/Kathmandu'],
  NR: ['Pacific/Nauru'],
  NU: ['Pacific/Niue'],
  NZ: ['Pacific/Auckland', 'Pacific/Chatham'],
  OM: ['Asia/Muscat'],
  PA: ['America/Panama'],
  PE: ['America/Lima'],
  PF: ['Pacific/Tahiti', 'Pacific/Marquesas', 'Pacific/Gambier'],
  PG: ['Pacific/Port_Moresby'],
  PH: ['Asia/Manila'],
  PK: ['Asia/Karachi'],
  PL: ['Europe/Warsaw'],
  PM: ['America/Miquelon'],
  PN: ['Pacific/Pitcairn'],
  PR: ['America/Puerto_Rico'],
  PS: ['Asia/Gaza', 'Asia/Hebron'],
  PT: ['Europe/Lisbon', 'Atlantic/Madeira', 'Atlantic/Azores'],
  PW: ['Pacific/Palau'],
  PY: ['America/Asuncion'],
  QA: ['Asia/Qatar'],
  RE: ['Indian/Reunion'],
  RO: ['Europe/Bucharest'],
  RS: ['Europe/Belgrade'],
  RU: [
    'Europe/Kaliningrad',
    'Europe/Moscow',
    'Europe/Volgograd',
    'Europe/Samara',
    'Europe/Simferopol',
    'Asia/Yekaterinburg',
    'Asia/Omsk',
    'Asia/Novosibirsk',
    'Asia/Novokuznetsk',
    'Asia/Krasnoyarsk',
    'Asia/Irkutsk',
    'Asia/Yakutsk',
    'Asia/Khandyga',
    'Asia/Vladivostok',
    'Asia/Sakhalin',
    'Asia/Ust-Nera',
    'Asia/Magadan',
    'Asia/Kamchatka',
    'Asia/Anadyr'
  ],
  RW: ['Africa/Kigali'],
  SA: ['Asia/Riyadh'],
  SB: ['Pacific/Guadalcanal'],
  SC: ['Indian/Mahe'],
  SD: ['Africa/Khartoum'],
  SE: ['Europe/Stockholm'],
  SG: ['Asia/Singapore'],
  SH: ['Atlantic/St_Helena'],
  SI: ['Europe/Ljubljana'],
  SJ: ['Arctic/Longyearbyen'],
  SK: ['Europe/Bratislava'],
  SL: ['Africa/Freetown'],
  SM: ['Europe/San_Marino'],
  SN: ['Africa/Dakar'],
  SO: ['Africa/Mogadishu'],
  SR: ['America/Paramaribo'],
  SS: ['Africa/Juba'],
  ST: ['Africa/Sao_Tome'],
  SV: ['America/El_Salvador'],
  SX: ['America/Lower_Princes'],
  SY: ['Asia/Damascus'],
  SZ: ['Africa/Mbabane'],
  TC: ['America/Grand_Turk'],
  TD: ['Africa/Ndjamena'],
  TF: ['Indian/Kerguelen'],
  TG: ['Africa/Lome'],
  TH: ['Asia/Bangkok'],
  TJ: ['Asia/Dushanbe'],
  TK: ['Pacific/Fakaofo'],
  TL: ['Asia/Dili'],
  TM: ['Asia/Ashgabat'],
  TN: ['Africa/Tunis'],
  TO: ['Pacific/Tongatapu'],
  TR: ['Europe/Istanbul'],
  TT: ['America/Port_of_Spain'],
  TV: ['Pacific/Funafuti'],
  TW: ['Asia/Taipei'],
  TZ: ['Africa/Dar_es_Salaam'],
  UA: ['Europe/Kiev', 'Europe/Uzhgorod', 'Europe/Zaporozhye'],
  UG: ['Africa/Kampala'],
  UM: ['Pacific/Johnston', 'Pacific/Midway', 'Pacific/Wake'],
  US: [
    'America/New_York',
    'America/Detroit',
    'America/Kentucky/Louisville',
    'America/Kentucky/Monticello',
    'America/Indiana/Indianapolis',
    'America/Indiana/Vincennes',
    'America/Indiana/Winamac',
    'America/Indiana/Marengo',
    'America/Indiana/Petersburg',
    'America/Indiana/Vevay',
    'America/Chicago',
    'America/Indiana/Tell_City',
    'America/Indiana/Knox',
    'America/Menominee',
    'America/North_Dakota/Center',
    'America/North_Dakota/New_Salem',
    'America/North_Dakota/Beulah',
    'America/Denver',
    'America/Boise',
    'America/Phoenix',
    'America/Los_Angeles',
    'America/Anchorage',
    'America/Juneau',
    'America/Sitka',
    'America/Yakutat',
    'America/Nome',
    'America/Adak',
    'America/Metlakatla',
    'Pacific/Honolulu'
  ],
  UY: ['America/Montevideo'],
  UZ: ['Asia/Samarkand', 'Asia/Tashkent'],
  VA: ['Europe/Vatican'],
  VC: ['America/St_Vincent'],
  VE: ['America/Caracas'],
  VG: ['America/Tortola'],
  VI: ['America/St_Thomas'],
  VN: ['Asia/Ho_Chi_Minh'],
  VU: ['Pacific/Efate'],
  WF: ['Pacific/Wallis'],
  WS: ['Pacific/Apia'],
  YE: ['Asia/Aden'],
  YT: ['Indian/Mayotte'],
  ZA: ['Africa/Johannesburg'],
  ZM: ['Africa/Lusaka'],
  ZW: ['Africa/Harare']
};

const countryList = {
  AF: 'Afghanistan',
  AX: 'Aland Islands',
  AL: 'Albania',
  DZ: 'Algeria',
  AS: 'American Samoa',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antarctica',
  AG: 'Antigua and Barbuda',
  AR: 'Argentina',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BS: 'Bahamas',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Belarus',
  BE: 'Belgium',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermuda',
  BT: 'Bhutan',
  BO: 'Bolivia',
  BA: 'Bosnia and Herzegovina',
  BW: 'Botswana',
  BV: 'Bouvet Island',
  BR: 'Brazil',
  VG: 'British Virgin Islands',
  IO: 'British Indian Ocean Territory',
  BN: 'Brunei Darussalam',
  BG: 'Bulgaria',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CA: 'Canada',
  CV: 'Cape Verde',
  KY: 'Cayman Islands',
  CF: 'Central African Republic',
  TD: 'Chad',
  CL: 'Chile',
  CN: 'China',
  HK: 'Hong Kong',
  MO: 'Macao',
  CX: 'Christmas Island',
  CC: 'Cocos (Keeling) Islands',
  CO: 'Colombia',
  KM: 'Comoros',
  CG: 'Congo (Brazzaville)',
  CD: 'Congo (Kinshasa)',
  CK: 'Cook Islands',
  CR: 'Costa Rica',
  CI: 'Ivory Coast',
  HR: 'Croatia',
  CU: 'Cuba',
  CW: 'Curacao',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DK: 'Denmark',
  DJ: 'Djibouti',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'El Salvador',
  GQ: 'Equatorial Guinea',
  ER: 'Eritrea',
  EE: 'Estonia',
  ET: 'Ethiopia',
  FK: 'Falkland Islands',
  FO: 'Faroe Islands',
  FJ: 'Fiji',
  FI: 'Finland',
  FR: 'France',
  GF: 'French Guiana',
  PF: 'French Polynesia',
  TF: 'French Southern Territories',
  GA: 'Gabon',
  GM: 'Gambia',
  GE: 'Georgia',
  DE: 'Germany',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GR: 'Greece',
  GL: 'Greenland',
  GD: 'Grenada',
  GP: 'Guadeloupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GG: 'Guernsey',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HT: 'Haiti',
  HM: 'Heard and Mcdonald Islands',
  VA: 'Vatican City State',
  HN: 'Honduras',
  HU: 'Hungary',
  IS: 'Iceland',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran',
  IQ: 'Iraq',
  IE: 'Ireland',
  IM: 'Isle of Man',
  IL: 'Israel',
  IT: 'Italy',
  JM: 'Jamaica',
  JP: 'Japan',
  JE: 'Jersey',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KI: 'Kiribati',
  KP: 'North Korea',
  KR: 'South Korea',
  KW: 'Kuwait',
  KG: 'Kyrgyzstan',
  LA: 'Laos',
  LV: 'Latvia',
  LB: 'Lebanon',
  LS: 'Lesotho',
  LR: 'Liberia',
  LY: 'Libya',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MK: 'Macedonia',
  MG: 'Madagascar',
  MW: 'Malawi',
  MY: 'Malaysia',
  MV: 'Maldives',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Marshall Islands',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MU: 'Mauritius',
  YT: 'Mayotte',
  MX: 'Mexico',
  FM: 'Micronesia',
  MD: 'Moldova',
  MC: 'Monaco',
  MN: 'Mongolia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MA: 'Morocco',
  MZ: 'Mozambique',
  MM: 'Myanmar',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Netherlands',
  AN: 'Netherlands Antilles',
  NC: 'New Caledonia',
  NZ: 'New Zealand',
  NI: 'Nicaragua',
  NE: 'Niger',
  NG: 'Nigeria',
  NU: 'Niue',
  NF: 'Norfolk Island',
  MP: 'Northern Mariana Islands',
  NO: 'Norway',
  OM: 'Oman',
  PK: 'Pakistan',
  PW: 'Palau',
  PS: 'Palestinian Territory',
  PA: 'Panama',
  PG: 'Papua New Guinea',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines',
  PN: 'Pitcairn',
  PL: 'Poland',
  PT: 'Portugal',
  PR: 'Puerto Rico',
  QA: 'Qatar',
  RE: 'Réunion',
  RO: 'Romania',
  RU: 'Russian Federation',
  RW: 'Rwanda',
  BL: 'Saint-Barthélemy',
  SH: 'Saint Helena',
  KN: 'Saint Kitts and Nevis',
  LC: 'Saint Lucia',
  MF: 'Saint-Martin (French part)',
  PM: 'Saint Pierre and Miquelon',
  VC: 'Saint Vincent and Grenadines',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'Sao Tome and Principe',
  SA: 'Saudi Arabia',
  SN: 'Senegal',
  RS: 'Serbia',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SG: 'Singapore',
  SX: 'Sint Maarten',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SB: 'Solomon Islands',
  SO: 'Somalia',
  ZA: 'South Africa',
  GS: 'South Georgia and the South Sandwich Islands',
  SS: 'South Sudan',
  ES: 'Spain',
  LK: 'Sri Lanka',
  SD: 'Sudan',
  SR: 'Suriname',
  SJ: 'Svalbard and Jan Mayen Islands',
  SZ: 'Swaziland',
  SE: 'Sweden',
  CH: 'Switzerland',
  SY: 'Syria',
  TW: 'Taiwan',
  TJ: 'Tajikistan',
  TZ: 'Tanzania',
  TH: 'Thailand',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad and Tobago',
  TN: 'Tunisia',
  TR: 'Turkey',
  TM: 'Turkmenistan',
  TC: 'Turks and Caicos Islands',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ukraine',
  AE: 'United Arab Emirates',
  GB: 'United Kingdom (GB)',
  US: 'United States (USA)',
  UM: 'US Minor Outlying Islands',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VU: 'Vanuatu',
  VE: 'Venezuela',
  VN: 'Vietnam',
  VI: 'Virgin Islands, US',
  WF: 'Wallis and Futuna Islands',
  EH: 'Western Sahara',
  YE: 'Yemen',
  ZM: 'Zambia',
  ZW: 'Zimbabwe'
};

const simpleZones: Zone[] = [
  { zone: 'Pacific/Midway', name: 'Midway Island, American Samoa' },
  { zone: 'America/Adak', name: 'Aleutian Islands' },
  { zone: 'Pacific/Honolulu', name: 'Hawaii' },
  { zone: 'Pacific/Marquesas', name: 'Marquesas Islands' },
  { zone: 'America/Anchorage', name: 'Alaska' },
  { zone: 'America/Tijuana', name: 'Baja California' },
  { zone: 'America/Los_Angeles', name: 'Pacific Time (US and Canada)' },
  { zone: 'America/Phoenix', name: 'Arizona' },
  { zone: 'America/Chihuahua', name: 'Chihuahua, La Paz, Mazatlan' },
  { zone: 'America/Denver', name: 'Mountain Time (US and Canada)' },
  { zone: 'America/Belize', name: 'Central America' },
  { zone: 'America/Chicago', name: 'Central Time (US and Canada)' },
  { zone: 'Pacific/Easter', name: 'Easter Island' },
  { zone: 'America/Mexico_City', name: 'Guadalajara, Mexico City, Monterrey' },
  { zone: 'America/Regina', name: 'Saskatchewan' },
  { zone: 'America/Bogota', name: 'Bogota, Lima, Quito' },
  { zone: 'America/Cancun', name: 'Chetumal' },
  { zone: 'America/New_York', name: 'Eastern Time (US and Canada)' },
  { zone: 'America/Port-au-Prince', name: 'Haiti' },
  { zone: 'America/Havana', name: 'Havana' },
  { zone: 'America/Indiana/Indianapolis', name: 'Indiana (East)' },
  { zone: 'America/Asuncion', name: 'Asuncion' },
  { zone: 'America/Halifax', name: 'Atlantic Time (Canada)' },
  { zone: 'America/Caracas', name: 'Caracas' },
  { zone: 'America/Cuiaba', name: 'Cuiaba' },
  { zone: 'America/Manaus', name: 'Georgetown, La Paz, Manaus, San Juan' },
  { zone: 'America/Santiago', name: 'Santiago' },
  { zone: 'America/Grand_Turk', name: 'Turks and Caicos' },
  { zone: 'America/St_Johns', name: 'Newfoundland' },
  { zone: 'America/Fortaleza', name: 'Araguaina' },
  { zone: 'America/Sao_Paulo', name: 'Brasilia' },
  { zone: 'America/Cayenne', name: 'Cayenne, Fortaleza' },
  { zone: 'America/Buenos_Aires', name: 'City of Buenos Aires' },
  { zone: 'America/Godthab', name: 'Greenland' },
  { zone: 'America/Montevideo', name: 'Montevideo' },
  { zone: 'America/Miquelon', name: 'Saint Pierre and Miquelon' },
  { zone: 'America/Bahia', name: 'Salvador' },
  { zone: 'America/Noronha', name: 'Fernando de Noronha' },
  { zone: 'Atlantic/Azores', name: 'Azores' },
  { zone: 'Atlantic/Cape_Verde', name: 'Cabo Verde Islands' },
  { zone: 'Africa/Casablanca', name: 'Casablanca' },
  { zone: 'Europe/London', name: 'Dublin, Edinburgh, Lisbon, London' },
  { zone: 'Africa/Monrovia', name: 'Monrovia, Reykjavik' },
  {
    zone: 'Europe/Amsterdam',
    name: 'Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna'
  },
  {
    zone: 'Europe/Belgrade',
    name: 'Belgrade, Bratislava, Budapest, Ljubljana, Prague'
  },
  { zone: 'Europe/Brussels', name: 'Brussels, Copenhagen, Madrid, Paris' },
  { zone: 'Europe/Warsaw', name: 'Sarajevo, Skopje, Warsaw, Zagreb' },
  { zone: 'Africa/Algiers', name: 'West Central Africa' },
  { zone: 'Africa/Windhoek', name: 'Windhoek' },
  { zone: 'Asia/Amman', name: 'Amman' },
  { zone: 'Europe/Athens', name: 'Athens, Bucharest' },
  { zone: 'Asia/Beirut', name: 'Beirut' },
  { zone: 'Africa/Cairo', name: 'Cairo' },
  { zone: 'Asia/Damascus', name: 'Damascus' },
  { zone: 'Asia/Gaza', name: 'Gaza, Hebron' },
  { zone: 'Africa/Harare', name: 'Harare, Pretoria' },
  {
    zone: 'Europe/Helsinki',
    name: 'Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius'
  },
  { zone: 'Asia/Jerusalem', name: 'Jerusalem' },
  { zone: 'Europe/Kaliningrad', name: 'Kaliningrad' },
  { zone: 'Africa/Tripoli', name: 'Tripoli' },
  { zone: 'Asia/Baghdad', name: 'Baghdad' },
  { zone: 'Asia/Istanbul', name: 'Istanbul' },
  { zone: 'Asia/Kuwait', name: 'Kuwait, Riyadh' },
  { zone: 'Europe/Minsk', name: 'Minsk' },
  { zone: 'Europe/Moscow', name: 'Moscow, St. Petersburg, Volgograd' },
  { zone: 'Africa/Nairobi', name: 'Nairobi' },
  { zone: 'Asia/Tehran', name: 'Tehran' },
  { zone: 'Asia/Muscat', name: 'Abu Dhabi, Muscat' },
  { zone: 'Europe/Astrakhan', name: 'Astrakhan, Ulyanovsk' },
  { zone: 'Asia/Baku', name: 'Baku' },
  { zone: 'Europe/Samara', name: 'Izhevsk, Samara' },
  { zone: 'Indian/Mauritius', name: 'Port Louis' },
  { zone: 'Asia/Tbilisi', name: 'Tbilisi' },
  { zone: 'Asia/Yerevan', name: 'Yerevan' },
  { zone: 'Asia/Kabul', name: 'Kabul' },
  { zone: 'Asia/Tashkent', name: 'Tashkent, Ashgabat' },
  { zone: 'Asia/Yekaterinburg', name: 'Ekaterinburg' },
  { zone: 'Asia/Karachi', name: 'Islamabad, Karachi' },
  { zone: 'Asia/Kolkata', name: 'Chennai, Kolkata, Mumbai, New Delhi' },
  { zone: 'Asia/Colombo', name: 'Sri Jayawardenepura' },
  { zone: 'Asia/Katmandu', name: 'Kathmandu' },
  { zone: 'Asia/Almaty', name: 'Astana' },
  { zone: 'Asia/Dhaka', name: 'Dhaka' },
  { zone: 'Asia/Rangoon', name: 'Yangon (Rangoon)' },
  { zone: 'Asia/Novosibirsk', name: 'Novosibirsk' },
  { zone: 'Asia/Bangkok', name: 'Bangkok, Hanoi, Jakarta' },
  { zone: 'Asia/Barnaul', name: 'Barnaul, Gorno-Altaysk' },
  { zone: 'Asia/Hovd', name: 'Hovd' },
  { zone: 'Asia/Krasnoyarsk', name: 'Krasnoyarsk' },
  { zone: 'Asia/Tomsk', name: 'Tomsk' },
  { zone: 'Asia/Chongqing', name: 'Beijing, Chongqing, Hong Kong SAR, Urumqi' },
  { zone: 'Asia/Irkutsk', name: 'Irkutsk' },
  { zone: 'Asia/Kuala_Lumpur', name: 'Kuala Lumpur, Singapore' },
  { zone: 'Australia/Perth', name: 'Perth' },
  { zone: 'Asia/Taipei', name: 'Taipei' },
  { zone: 'Asia/Ulaanbaatar', name: 'Ulaanbaatar' },
  { zone: 'Asia/Pyongyang', name: 'Pyongyang' },
  { zone: 'Australia/Eucla', name: 'Eucla' },
  { zone: 'Asia/Chita', name: 'Chita' },
  { zone: 'Asia/Tokyo', name: 'Osaka, Sapporo, Tokyo' },
  { zone: 'Asia/Seoul', name: 'Seoul' },
  { zone: 'Asia/Yakutsk', name: 'Yakutsk' },
  { zone: 'Australia/Adelaide', name: 'Adelaide' },
  { zone: 'Australia/Darwin', name: 'Darwin' },
  { zone: 'Australia/Brisbane', name: 'Brisbane' },
  { zone: 'Australia/Canberra', name: 'Canberra, Melbourne, Sydney' },
  { zone: 'Pacific/Guam', name: 'Guam, Port Moresby' },
  { zone: 'Australia/Hobart', name: 'Hobart' },
  { zone: 'Asia/Vladivostok', name: 'Vladivostok' },
  { zone: 'Australia/Lord_Howe', name: 'Lord Howe Island' },
  { zone: 'Pacific/Bougainville', name: 'Bougainville Island' },
  { zone: 'Asia/Srednekolymsk', name: 'Chokirdakh' },
  { zone: 'Asia/Magadan', name: 'Magadan' },
  { zone: 'Pacific/Norfolk', name: 'Norfolk Island' },
  { zone: 'Asia/Sakhalin', name: 'Sakhalin' },
  { zone: 'Pacific/Guadalcanal', name: 'Solomon Islands, New Caledonia' },
  { zone: 'Asia/Anadyr', name: 'Anadyr, Petropavlovsk-Kamchatsky' },
  { zone: 'Pacific/Auckland', name: 'Auckland, Wellington' },
  { zone: 'Pacific/Fiji', name: 'Fiji Islands' },
  { zone: 'Pacific/Chatham', name: 'Chatham Islands' },
  { zone: 'Pacific/Tongatapu', name: 'Nuku\'alofa' },
  { zone: 'Pacific/Apia', name: 'Samoa' },
  { zone: 'Pacific/Kiritimati', name: 'Kiritimati Island' }
];
